TTScorer/Models/ApplicationDbContext.cs
namespace TTScorer.Models;

using Microsoft.EntityFrameworkCore;

public class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public DbSet<Player> Players { get; set; }
    public DbSet<Match> Matches { get; set; }
    public DbSet<Score> Scores { get; set; }
}

TTScorer/Models/ErrorViewModel.cs
namespace TTScorer.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

TTScorer/Models/Match.cs
namespace TTScorer.Models;

public class Match
{
    public int Id { get; set; }
    public DateTime MatchDate { get; set; }

    public ICollection<Score> Scores { get; set; }

}

TTScorer/Models/Player.cs
namespace TTScorer.Models
{
    public class Player
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public ICollection<Score> Scores { get; set; }
    }
}

TTScorer/Models/Score.cs
namespace TTScorer.Models;

public class Score
{
    public int Id { get; set; }
    public Player Player { get; set; }
    public Match Match { get; set; }
    public int Points { get; set; }
}

TTScorer/Models/ScoreEntryViewModel.cs
namespace TTScorer.Models;

public class ScoreEntryViewModel
{
    public int Player1Id { get; set; }
    public int Player2Id { get; set; }
    public int Player1Score { get; set; }
    public int Player2Score { get; set; }
}

TTScorer/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TTScorer.Models;
using Microsoft.EntityFrameworkCore;

namespace TTScorer.Controllers;

public class HomeController : Controller
{
    private readonly ApplicationDbContext _dbContext;
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger, ApplicationDbContext dbContext)
    {
        _logger = logger;
        _dbContext = dbContext;
    }

    public IActionResult Index()
    {
        var players = _dbContext.Players.ToList();
        return View(players);
    }

    public async Task<IActionResult> Results()
    {
        var recentMatches = await _dbContext.Matches
            .Include(m => m.Scores)
            .ThenInclude(p => p.Player)
            .Take(10)
            .ToListAsync();

        return View(recentMatches);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    [HttpPost]
    public async Task<IActionResult> RegisterScore(ScoreEntryViewModel scoreEntry)
    {
        Player player1 = _dbContext.Players.Find(scoreEntry.Player1Id);
        Player player2 = _dbContext.Players.Find(scoreEntry.Player2Id);

        Match newMatch = new Match()
        {
            MatchDate = DateTime.Now
        };

        _dbContext.Matches.Add(newMatch);
        _dbContext.SaveChanges();

        var matchId = _dbContext.Matches.Find(newMatch.Id);

        Score player1Score = new Score()
        {
            Match = matchId,
            Player = player1,
            Points = scoreEntry.Player1Score
        };

        Score player2Score = new Score()
        {
            Match = matchId,
            Player = player2,
            Points = scoreEntry.Player2Score
        };

        _dbContext.Scores.Add(player1Score);
        _dbContext.Scores.Add(player2Score);
        _dbContext.SaveChanges();

        if (!ModelState.IsValid) return View("Index");

        return RedirectToAction("Index");
    }
}

TTScorer/Controllers/PlayerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TTScorer.Models;

namespace TTScorer.Controllers;

public class PlayerController : Controller
{
    private readonly ApplicationDbContext _dbContext;
    private readonly ILogger<PlayerController> _logger;

    public PlayerController(ILogger<PlayerController> logger, ApplicationDbContext dbContext)
    {
        _logger = logger;
        _dbContext = dbContext;
    }

    public async Task<IActionResult> Index()
    {
        var players = await _dbContext.Players.ToListAsync();

        return View(players);
    }

    public ActionResult CreatePlayer()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreatePlayer(Player player)
    {
        _dbContext.Players.Add(player);
        await _dbContext.SaveChangesAsync();

        return RedirectToAction("Index");
    }

    public async Task<IActionResult> PlayerDetails(int playerId)
    {
        var player = await _dbContext.Players.FindAsync(playerId);
        return View(player);
    }

    public async Task<IActionResult> DeletePlayer(int playerId)
    {
        var player = await _dbContext.Players.FindAsync(playerId);
        _dbContext.Players.Remove(player);
        await _dbContext.SaveChangesAsync();

        return RedirectToAction("Index");
    }
}

TTScorer/Views/Home/Index.cshtml
@model IEnumerable<TTScorer.Models.Player>;

@{
    ViewData["Title"] = "Home";
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<div class="container mt-5">
    <h2 class="mb-4">Experis Table Tennis Scorer</h2>
    <form asp-controller="Home" asp-action="RegisterScore" method="post">
        <div class="row">
            <div class="col-sm">
            </div>
            <div class="col-sm">
                <div class="row">
                    <label class="form-label" for="player1id">Player 1:</label>
                </div>
                <div class="row">
                    <select value="" id="player1id" name="player1id">
                        @foreach(var player in Model)
                        {
                            <option value=@player.Id>@player.Name</option>
                        }
                    </select>
                </div>
            </div>
            <div class="col-sm">
                <div class="row">
                    <label class="form-label" for="player2id">Player 2:</label>
                </div>
                <div class="row">
                    <select id="player2id" name="player2id">
                        @foreach(var player in Model)
                        {
                            <option value=@player.Id>@player.Name</option>
                        }
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <label class="form-label">Score</label>
            </div>
            <div class="col-sm">
                <input type="number" class="form-control" id="player1score" name="player1score" min="0" required>
            </div>
            <div class="col-sm">
                <input type="number" class="form-control" id="player2score" name="player2score" min="0" required>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

TTScorer/Views/Home/Results.cshtml
@model IEnumerable<TTScorer.Models.Match>


  @{ ViewData["Title"] = "Results"; }

  <head>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
  </head>

  <h2>Recent Matches</h2>

  <table class="table">
    <thead>
      <tr>
        <th>Player 1</th>
        <th>Player 2</th>
        <th>Score 1</th>
        <th>Score 2</th>
      </tr>
    </thead>
    <tbody>
      @foreach (var match in Model) {
      <tr>
        @if (match.Scores.First().Points > match.Scores.Last().Points) {
        <td>@match.Scores.First().Player.Name <i class="fa fa-trophy" /></td>
        <td>@match.Scores.Last().Player.Name</td>
        } else {
        <td>@match.Scores.First().Player.Name</td>
        <td>@match.Scores.Last().Player.Name <i class="fa fa-trophy" /></td>
        }
        <td>@match.Scores.First().Points</td>
        <td>@match.Scores.Last().Points</td>
      </tr>
      }
    </tbody>
  </table>

TTScorer/Views/Player/CreatePlayer.cshtml
@{ ViewData["Title"] = "Create Player"; }

<div class="container mt-5">
    <h2 class="mb-4">Crate Player</h2>
    <form asp-controller="Player" asp-action="CreatePlayer" method="post">
        <div class="form-group">
            <label class="form-label" for="Name">Name:</label>
            <input type="text" class="form-control" id="name" name="Name" required /> 
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>

TTScorer/Views/Player/Index.cshtml
@model IEnumerable<TTScorer.Models.Player>;

@{
  ViewData["Title"] = "Players";
}

<div class="container mt-5">
  <h2 class="mb-4">Players</h2>
  <div>
    @foreach(var player in Model)
    {
      <a class="nav-link text-dark" asp-controller="Player" asp-action="PlayerDetails" asp-route-playerId=@player.Id>@player.Name</a>
    }
  </div>
  <input type="button" value="Create player" onclick="location.href='@Url.Action("CreatePlayer", "Player")'" />
</div>

TTScorer/Views/Player/PlayerDetails.cshtml
@model TTScorer.Models.Player;

@{
  ViewData["Title"] = "Player Details";
}

<div class="container mt-5">
  <h2 class="mb-4">Player Details</h2>
  <div>Name:</div>
  <div>@Model.Name</div>
  <input type="button" value="Delete player" onclick="location.href='@Url.Action("DeletePlayer", "Player", new {playerId = @Model.Id})'" />   
</div>

TTScorer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>@ViewData["Title"] - TTScorer</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/TTScorer.styles.css" asp-append-version="true"/>
        <link rel="icon" type="image/png" sizes="255x255" href="~/experis_logo_225x225.png">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 dark-mode">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TTScorer</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Results">Results</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Index">Players</a>
                    </li>
                </ul>
                <li class="nav-item ml-auto d-flex align-items-center">
                    <span id="darkModeText" class="nav-link text-dark">Dark Mode:</span>
                    <label class="switch">
                        <input type="checkbox" id="darkModeToggle">
                        <span class="slider round"></span>
                    </label>
                </li>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - TTScorer - <a asp-area="" asp-controller="Home" asp-action="Results">Results</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)

<!-- JavaScript for dark mode toggle -->
<script>
    var checkbox = document.querySelector('#darkModeToggle');
    var darkModeText = document.querySelector('#darkModeText');
    var mainNavbar = document.querySelector('.navbar');

    checkbox.addEventListener('change', function() {
        if(this.checked) {
            document.body.classList.add('dark-mode');
            darkModeText.classList.add('dark-mode-text');
            mainNavbar.classList.add('dark-mode');
            console.log("Dark mode enabled");
        } else {
            document.body.classList.remove('dark-mode');
            darkModeText.classList.remove('dark-mode-text');
            mainNavbar.classList.remove('dark-mode');
            console.log("Dark mode disabled");
        }
    });
</script>

</body>
</html>